"""
Full test suite for Mission Control platforms app.
"""
from datetime import datetime, timezone
from unittest.mock import patch, MagicMock

from django.contrib.auth.models import User
from django.test import TestCase, Client
from django.urls import reverse

from django.utils import timezone

from .models import (
    Platform, Repository, Host, Service, Domain, Deployment, HealthCheck,
    LifecycleStatus, HealthStatus, PlatformType, FrameworkChoice,
    EnvironmentChoice, DeploymentStatus, ActivityEntry, ActivityType,
)
from .services import run_health_check, get_default_service_name


# --------------------------------------------------------------------------- #
# Helpers                                                                      #
# --------------------------------------------------------------------------- #

def make_platform(**kwargs):
    defaults = dict(
        name='Test Platform',
        slug='test-platform',
        platform_type=PlatformType.WEBSITE,
        framework=FrameworkChoice.DJANGO,
        lifecycle_status=LifecycleStatus.DEVELOPMENT,
    )
    defaults.update(kwargs)
    return Platform.objects.create(**defaults)


def make_host(**kwargs):
    defaults = dict(name='Test Host', provider='other', host_type='vps', status='active')
    defaults.update(kwargs)
    return Host.objects.create(**defaults)


# --------------------------------------------------------------------------- #
# Model Tests                                                                  #
# --------------------------------------------------------------------------- #

class PlatformModelTests(TestCase):

    def test_create_minimal_platform(self):
        p = make_platform()
        self.assertEqual(p.name, 'Test Platform')
        self.assertEqual(p.slug, 'test-platform')
        self.assertEqual(p.lifecycle_status, LifecycleStatus.DEVELOPMENT)

    def test_slug_uniqueness_enforced(self):
        make_platform()
        from django.db import IntegrityError
        with self.assertRaises(Exception):
            make_platform()

    def test_slug_autogenerated_from_name(self):
        p = Platform(name='My Cool App')
        p.save()
        self.assertEqual(p.slug, 'my-cool-app')

    def test_platform_valid_without_repo(self):
        p = make_platform()
        self.assertFalse(p.repositories.exists())

    def test_platform_valid_without_host(self):
        p = make_platform()
        self.assertIsNone(p.primary_host)

    def test_platform_valid_without_domain(self):
        p = make_platform()
        self.assertIsNone(p.primary_domain)

    def test_health_status_unknown_with_no_checks(self):
        p = make_platform()
        self.assertEqual(p.health_status, HealthStatus.UNKNOWN)

    def test_health_status_reflects_latest_check(self):
        p = make_platform()
        HealthCheck.objects.create(
            platform=p, endpoint='http://example.com',
            status=HealthStatus.HEALTHY, checked_at=datetime.now(tz=timezone.utc),
        )
        self.assertEqual(p.health_status, HealthStatus.HEALTHY)

    def test_needs_attention_no_service(self):
        p = make_platform(lifecycle_status=LifecycleStatus.ACTIVE)
        issues = p.needs_attention()
        self.assertIn('No services configured', issues)

    def test_needs_attention_active_no_repo(self):
        p = make_platform(lifecycle_status=LifecycleStatus.ACTIVE)
        issues = p.needs_attention()
        self.assertIn('No repository configured', issues)

    def test_needs_attention_dev_no_domain_not_flagged(self):
        p = make_platform(lifecycle_status=LifecycleStatus.DEVELOPMENT)
        issues = p.needs_attention()
        self.assertNotIn('No domain configured', issues)

    def test_archive_lifecycle(self):
        p = make_platform(lifecycle_status=LifecycleStatus.ACTIVE)
        p.lifecycle_status = LifecycleStatus.ARCHIVED
        p.save()
        p.refresh_from_db()
        self.assertEqual(p.lifecycle_status, LifecycleStatus.ARCHIVED)

    def test_primary_domain_property(self):
        p = make_platform()
        Domain.objects.create(platform=p, hostname='example.com', is_primary=True, environment='production')
        Domain.objects.create(platform=p, hostname='www.example.com', is_primary=False, environment='production')
        self.assertEqual(p.primary_domain.hostname, 'example.com')


class DomainModelTests(TestCase):

    def test_hostname_normalized_on_save(self):
        p = make_platform()
        d = Domain.objects.create(platform=p, hostname='Example.COM/', is_primary=True, environment='production')
        self.assertEqual(d.hostname, 'example.com')

    def test_url_https_when_ssl_enabled(self):
        p = make_platform()
        d = Domain.objects.create(platform=p, hostname='example.com', is_primary=True, ssl_enabled=True, environment='production')
        self.assertEqual(d.url, 'https://example.com')

    def test_url_http_when_ssl_disabled(self):
        p = make_platform()
        d = Domain.objects.create(platform=p, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        self.assertEqual(d.url, 'http://example.com')


# --------------------------------------------------------------------------- #
# Health Check Service Tests                                                   #
# --------------------------------------------------------------------------- #

class HealthCheckServiceTests(TestCase):

    def setUp(self):
        self.platform = make_platform()

    def test_no_domain_returns_unknown(self):
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.UNKNOWN)
        self.assertIn('No endpoint', check.error_info)

    @patch('platforms.services.requests.get')
    def test_successful_check_marks_healthy(self, mock_get):
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_get.return_value = mock_response
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.HEALTHY)
        self.assertEqual(check.http_status, 200)

    @patch('platforms.services.requests.get')
    def test_500_marks_down(self, mock_get):
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        mock_response = MagicMock()
        mock_response.status_code = 500
        mock_get.return_value = mock_response
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.DOWN)

    @patch('platforms.services.requests.get')
    def test_timeout_marks_down(self, mock_get):
        from requests.exceptions import Timeout
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        mock_get.side_effect = Timeout()
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.DOWN)
        self.assertIn('timed out', check.error_info)

    @patch('platforms.services.requests.get')
    def test_connection_error_marks_down(self, mock_get):
        from requests.exceptions import ConnectionError
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        mock_get.side_effect = ConnectionError()
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.DOWN)

    @patch('platforms.services.requests.get')
    def test_ssl_error_marks_down(self, mock_get):
        from requests.exceptions import SSLError
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=True, environment='production')
        mock_get.side_effect = SSLError()
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.DOWN)
        self.assertIn('SSL', check.error_info)

    @patch('platforms.services.requests.get')
    def test_404_marks_degraded(self, mock_get):
        Domain.objects.create(platform=self.platform, hostname='example.com', is_primary=True, ssl_enabled=False, environment='production')
        mock_response = MagicMock()
        mock_response.status_code = 404
        mock_get.return_value = mock_response
        check = run_health_check(self.platform)
        self.assertEqual(check.status, HealthStatus.DEGRADED)

    def test_health_check_saved_to_database(self):
        check = run_health_check(self.platform)
        self.assertEqual(HealthCheck.objects.filter(platform=self.platform).count(), 1)
        self.assertEqual(HealthCheck.objects.get(pk=check.pk).platform, self.platform)

    def test_default_service_name_wagtail(self):
        name, stype = get_default_service_name('wagtail')
        self.assertEqual(name, 'Wagtail Application')

    def test_default_service_name_laravel(self):
        name, stype = get_default_service_name('laravel')
        self.assertEqual(name, 'Laravel Application')


# --------------------------------------------------------------------------- #
# View Tests (require auth)                                                    #
# --------------------------------------------------------------------------- #

class AuthenticatedTestCase(TestCase):

    def setUp(self):
        self.user = User.objects.create_user('testuser', password='testpass123')
        self.client = Client()
        self.client.login(username='testuser', password='testpass123')


class DashboardViewTests(AuthenticatedTestCase):

    def test_dashboard_loads_empty_db(self):
        resp = self.client.get(reverse('platforms:dashboard'))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.context['total'], 0)

    def test_dashboard_counts_platforms(self):
        make_platform(name='P1', slug='p1')
        make_platform(name='P2', slug='p2', lifecycle_status=LifecycleStatus.ACTIVE)
        resp = self.client.get(reverse('platforms:dashboard'))
        self.assertEqual(resp.context['total'], 2)
        self.assertEqual(resp.context['active_count'], 1)

    def test_dashboard_requires_login(self):
        self.client.logout()
        resp = self.client.get(reverse('platforms:dashboard'))
        self.assertRedirects(resp, '/accounts/login/?next=/')

    def test_dashboard_healthy_count(self):
        p = make_platform()
        HealthCheck.objects.create(
            platform=p, endpoint='http://x.com',
            status=HealthStatus.HEALTHY, checked_at=datetime.now(tz=timezone.utc)
        )
        resp = self.client.get(reverse('platforms:dashboard'))
        self.assertEqual(resp.context['healthy_count'], 1)


class PlatformListViewTests(AuthenticatedTestCase):

    def test_list_empty(self):
        resp = self.client.get(reverse('platforms:platform_list'))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.context['platform_data']), 0)

    def test_list_shows_platforms(self):
        make_platform(name='Alpha', slug='alpha')
        make_platform(name='Beta', slug='beta')
        resp = self.client.get(reverse('platforms:platform_list'))
        self.assertEqual(len(resp.context['platform_data']), 2)

    def test_search_filter(self):
        make_platform(name='Alpha Site', slug='alpha-site')
        make_platform(name='Beta App', slug='beta-app')
        resp = self.client.get(reverse('platforms:platform_list') + '?q=alpha')
        self.assertEqual(len(resp.context['platform_data']), 1)

    def test_lifecycle_filter(self):
        make_platform(name='Active', slug='active-p', lifecycle_status=LifecycleStatus.ACTIVE)
        make_platform(name='Dev', slug='dev-p', lifecycle_status=LifecycleStatus.DEVELOPMENT)
        resp = self.client.get(reverse('platforms:platform_list') + '?lifecycle=active')
        self.assertEqual(len(resp.context['platform_data']), 1)

    def test_framework_filter(self):
        make_platform(name='Wagtail', slug='wag', framework=FrameworkChoice.WAGTAIL)
        make_platform(name='Laravel', slug='lar', framework=FrameworkChoice.LARAVEL)
        resp = self.client.get(reverse('platforms:platform_list') + '?framework=wagtail')
        self.assertEqual(len(resp.context['platform_data']), 1)


class PlatformDetailViewTests(AuthenticatedTestCase):

    def test_detail_loads(self):
        p = make_platform()
        resp = self.client.get(reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.context['platform'], p)

    def test_detail_shows_relationships(self):
        p = make_platform()
        h = make_host()
        Service.objects.create(platform=p, host=h, name='Web', service_type='web', environment='production')
        Domain.objects.create(platform=p, hostname='example.com', is_primary=True, environment='production')
        resp = self.client.get(reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(resp.context['services'].count(), 1)
        self.assertEqual(resp.context['domains'].count(), 1)

    def test_detail_404_for_missing(self):
        resp = self.client.get(reverse('platforms:platform_detail', kwargs={'slug': 'nonexistent'}))
        self.assertEqual(resp.status_code, 404)


class PlatformArchiveTests(AuthenticatedTestCase):

    def test_archive_sets_lifecycle(self):
        p = make_platform(lifecycle_status=LifecycleStatus.ACTIVE)
        resp = self.client.post(reverse('platforms:platform_archive', kwargs={'slug': p.slug}))
        self.assertRedirects(resp, reverse('platforms:platform_list'))
        p.refresh_from_db()
        self.assertEqual(p.lifecycle_status, LifecycleStatus.ARCHIVED)


# --------------------------------------------------------------------------- #
# Wizard Tests                                                                 #
# --------------------------------------------------------------------------- #

class WizardTests(AuthenticatedTestCase):

    def _post_step(self, step, data):
        return self.client.post(reverse('platforms:wizard_step', kwargs={'step': step}), data)

    def _get_step(self, step):
        return self.client.get(reverse('platforms:wizard_step', kwargs={'step': step}))

    def test_wizard_start_clears_and_redirects(self):
        session = self.client.session
        session['platform_wizard'] = {'step1': {'name': 'old'}}
        session.save()
        resp = self.client.get(reverse('platforms:wizard_start'))
        self.assertRedirects(resp, reverse('platforms:wizard_step', kwargs={'step': 1}))
        self.assertNotIn('platform_wizard', self.client.session)

    def test_step1_renders(self):
        resp = self._get_step(1)
        self.assertEqual(resp.status_code, 200)

    def test_step1_valid_advances(self):
        resp = self._post_step(1, {
            'name': 'My Platform',
            'slug': 'my-platform',
            'platform_type': 'website',
            'lifecycle_status': 'development',
        })
        self.assertRedirects(resp, reverse('platforms:wizard_step', kwargs={'step': 2}))
        self.assertIn('step1', self.client.session['platform_wizard'])

    def test_step1_empty_name_invalid(self):
        resp = self._post_step(1, {'name': '', 'slug': '', 'platform_type': 'website', 'lifecycle_status': 'development'})
        self.assertEqual(resp.status_code, 200)
        self.assertFormError(resp.context['form'], 'name', 'This field is required.')

    def test_step2_cannot_access_without_step1(self):
        resp = self._get_step(2)
        self.assertRedirects(resp, reverse('platforms:wizard_step', kwargs={'step': 1}))

    def _complete_wizard(self, overrides=None):
        data = {
            'step1': {'name': 'Full Platform', 'slug': 'full-platform', 'platform_type': 'website', 'lifecycle_status': 'development'},
            'step2': {'framework': 'django', 'default_environment': 'development'},
            'step3': {'repo_option': 'none'},
            'step4': {'host_option': 'none'},
            'step5': {'domain_option': 'none'},
            'step6': {'service_name': 'Web App', 'service_type': 'web', 'service_environment': 'development', 'skip_service': False},
        }
        if overrides:
            data.update(overrides)
        session = self.client.session
        session['platform_wizard'] = {
            'step1': data['step1'],
            'step2': data['step2'],
            'step3': data['step3'],
            'step4': data['step4'],
            'step5': data['step5'],
            'step6': data['step6'],
        }
        session.save()
        return self.client.post(reverse('platforms:wizard_complete'))

    def test_wizard_completion_creates_platform(self):
        resp = self._complete_wizard()
        self.assertEqual(Platform.objects.filter(slug='full-platform').count(), 1)
        p = Platform.objects.get(slug='full-platform')
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))

    def test_wizard_completion_creates_service(self):
        self._complete_wizard()
        p = Platform.objects.get(slug='full-platform')
        self.assertEqual(p.services.count(), 1)
        self.assertEqual(p.services.first().name, 'Web App')

    def test_wizard_completion_without_repo(self):
        self._complete_wizard()
        p = Platform.objects.get(slug='full-platform')
        self.assertEqual(p.repositories.count(), 0)

    def test_wizard_completion_without_host(self):
        self._complete_wizard()
        p = Platform.objects.get(slug='full-platform')
        self.assertIsNone(p.services.first().host)

    def test_wizard_completion_without_domain(self):
        self._complete_wizard()
        p = Platform.objects.get(slug='full-platform')
        self.assertEqual(p.domains.count(), 0)

    def test_wizard_with_repository(self):
        session = self.client.session
        session['platform_wizard'] = {
            'step1': {'name': 'Repo Platform', 'slug': 'repo-platform', 'platform_type': 'website', 'lifecycle_status': 'development'},
            'step2': {'framework': 'django', 'default_environment': 'development'},
            'step3': {'repo_option': 'new', 'repo_name': 'my-repo', 'repo_provider': 'github', 'repo_url': 'https://github.com/test/repo', 'repo_default_branch': 'main'},
            'step4': {'host_option': 'none'},
            'step5': {'domain_option': 'none'},
            'step6': {'skip_service': True},
        }
        session.save()
        self.client.post(reverse('platforms:wizard_complete'))
        p = Platform.objects.get(slug='repo-platform')
        self.assertEqual(p.repositories.count(), 1)
        self.assertEqual(p.repositories.first().name, 'my-repo')

    def test_wizard_with_inline_host(self):
        session = self.client.session
        session['platform_wizard'] = {
            'step1': {'name': 'Host Platform', 'slug': 'host-platform', 'platform_type': 'website', 'lifecycle_status': 'development'},
            'step2': {'framework': 'django', 'default_environment': 'development'},
            'step3': {'repo_option': 'none'},
            'step4': {'host_option': 'new', 'host_name': 'My Server', 'host_provider': 'digitalocean', 'host_hostname': '1.2.3.4', 'host_environment': 'production', 'host_type': 'vps'},
            'step5': {'domain_option': 'none'},
            'step6': {'skip_service': False, 'service_name': 'App', 'service_type': 'web', 'service_environment': 'production'},
        }
        session.save()
        self.client.post(reverse('platforms:wizard_complete'))
        p = Platform.objects.get(slug='host-platform')
        self.assertTrue(Host.objects.filter(name='My Server').exists())
        self.assertEqual(p.services.first().host.name, 'My Server')

    def test_wizard_with_domain(self):
        session = self.client.session
        session['platform_wizard'] = {
            'step1': {'name': 'Domain Platform', 'slug': 'domain-platform', 'platform_type': 'website', 'lifecycle_status': 'active'},
            'step2': {'framework': 'wagtail', 'default_environment': 'production'},
            'step3': {'repo_option': 'none'},
            'step4': {'host_option': 'none'},
            'step5': {
                'domain_option': 'add',
                'primary_domain': 'mysite.com',
                'extra_domains': 'www.mysite.com\napi.mysite.com',
                'domain_environment': 'production',
                'ssl_enabled': 'True',
            },
            'step6': {'skip_service': True},
        }
        session.save()
        self.client.post(reverse('platforms:wizard_complete'))
        p = Platform.objects.get(slug='domain-platform')
        self.assertEqual(p.domains.count(), 3)
        self.assertTrue(p.domains.filter(hostname='mysite.com', is_primary=True).exists())

    def test_wizard_transactional_on_failure(self):
        session = self.client.session
        session['platform_wizard'] = {
            'step1': {'name': 'Fail Platform', 'slug': 'fail-platform', 'platform_type': 'website', 'lifecycle_status': 'development'},
            'step2': {'framework': 'django', 'default_environment': 'development'},
            'step3': {'repo_option': 'none'},
            'step4': {'host_option': 'none'},
            'step5': {'domain_option': 'none'},
            'step6': {'skip_service': False, 'service_name': 'App', 'service_type': 'web', 'service_environment': 'development'},
        }
        session.save()
        # First completion OK
        self.client.post(reverse('platforms:wizard_complete'))
        self.assertEqual(Platform.objects.filter(slug='fail-platform').count(), 1)

    def test_wizard_expired_session_redirects(self):
        resp = self.client.post(reverse('platforms:wizard_complete'))
        self.assertRedirects(resp, reverse('platforms:wizard_start'), fetch_redirect_response=False)

    def test_wizard_existing_host_selection(self):
        host = make_host(name='Shared Host')
        session = self.client.session
        session['platform_wizard'] = {
            'step1': {'name': 'Existing Host Platform', 'slug': 'exist-host', 'platform_type': 'website', 'lifecycle_status': 'development'},
            'step2': {'framework': 'django', 'default_environment': 'development'},
            'step3': {'repo_option': 'none'},
            'step4': {'host_option': 'existing', 'host_id': host.pk},
            'step5': {'domain_option': 'none'},
            'step6': {'skip_service': False, 'service_name': 'App', 'service_type': 'web', 'service_environment': 'development'},
        }
        session.save()
        self.client.post(reverse('platforms:wizard_complete'))
        p = Platform.objects.get(slug='exist-host')
        self.assertEqual(p.services.first().host, host)


# --------------------------------------------------------------------------- #
# CRUD Tests                                                                   #
# --------------------------------------------------------------------------- #

class RepositoryCRUDTests(AuthenticatedTestCase):

    def test_add_repository(self):
        p = make_platform()
        resp = self.client.post(
            reverse('platforms:repository_add', kwargs={'slug': p.slug}),
            {'name': 'My Repo', 'provider': 'github', 'url': 'https://github.com/x/y', 'default_branch': 'main', 'status': 'active'}
        )
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(p.repositories.count(), 1)

    def test_edit_repository(self):
        p = make_platform()
        repo = Repository.objects.create(platform=p, name='Old Name', provider='github', default_branch='main')
        self.client.post(
            reverse('platforms:repository_edit', kwargs={'slug': p.slug, 'pk': repo.pk}),
            {'name': 'New Name', 'provider': 'github', 'url': '', 'default_branch': 'develop', 'status': 'active'}
        )
        repo.refresh_from_db()
        self.assertEqual(repo.name, 'New Name')


class HostCRUDTests(AuthenticatedTestCase):

    def test_create_host(self):
        resp = self.client.post(
            reverse('platforms:host_create'),
            {'name': 'New Host', 'provider': 'digitalocean', 'hostname': '1.2.3.4',
             'environment': 'production', 'host_type': 'vps', 'status': 'active', 'notes': ''}
        )
        self.assertRedirects(resp, reverse('platforms:host_list'))
        self.assertEqual(Host.objects.filter(name='New Host').count(), 1)


class ServiceCRUDTests(AuthenticatedTestCase):

    def test_add_service(self):
        p = make_platform()
        resp = self.client.post(
            reverse('platforms:service_add', kwargs={'slug': p.slug}),
            {'name': 'App', 'service_type': 'web', 'environment': 'production', 'status': 'unknown'}
        )
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(p.services.count(), 1)


class DomainCRUDTests(AuthenticatedTestCase):

    def test_add_domain(self):
        p = make_platform()
        resp = self.client.post(
            reverse('platforms:domain_add', kwargs={'slug': p.slug}),
            {'hostname': 'example.com', 'environment': 'production', 'is_primary': True, 'status': 'active'}
        )
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(p.domains.count(), 1)


class DeploymentCRUDTests(AuthenticatedTestCase):

    def test_record_deployment(self):
        p = make_platform()
        resp = self.client.post(
            reverse('platforms:deployment_add', kwargs={'slug': p.slug}),
            {
                'environment': 'production',
                'version': 'v1.0.0',
                'status': 'success',
                'deployed_at': '2026-01-01T12:00',
                'deployed_by': 'ci',
                'notes': '',
            }
        )
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(p.deployments.count(), 1)
        self.assertEqual(p.deployments.first().version, 'v1.0.0')


# --------------------------------------------------------------------------- #
# Activity Log Tests                                                           #
# --------------------------------------------------------------------------- #

def make_activity(platform=None, **kwargs):
    defaults = dict(
        title='Test activity',
        activity_type=ActivityType.DEVELOPMENT,
        occurred_at=timezone.now(),
    )
    defaults.update(kwargs)
    return ActivityEntry.objects.create(platform=platform, **defaults)


class ActivityEntryModelTests(TestCase):

    def test_create_minimal_entry(self):
        p = make_platform()
        e = make_activity(platform=p)
        self.assertEqual(e.title, 'Test activity')
        self.assertEqual(e.activity_type, ActivityType.DEVELOPMENT)
        self.assertFalse(e.is_milestone)

    def test_estate_wide_entry_has_null_platform(self):
        e = make_activity(platform=None, title='Estate event')
        self.assertIsNone(e.platform)

    def test_default_ordering_is_newest_first(self):
        p = make_platform()
        now = timezone.now()
        from datetime import timedelta
        e1 = make_activity(p, title='Older', occurred_at=now - timedelta(days=2))
        e2 = make_activity(p, title='Newer', occurred_at=now)
        entries = list(ActivityEntry.objects.all())
        self.assertEqual(entries[0], e2)
        self.assertEqual(entries[1], e1)

    def test_str_returns_title(self):
        e = make_activity(title='Deploy v2')
        self.assertEqual(str(e), 'Deploy v2')

    def test_milestone_flag(self):
        e = make_activity(is_milestone=True)
        self.assertTrue(e.is_milestone)

    def test_created_by_nullable(self):
        e = make_activity()
        self.assertIsNone(e.created_by)


class ActivityLogViewTests(AuthenticatedTestCase):

    def test_activity_log_requires_login(self):
        self.client.logout()
        resp = self.client.get(reverse('platforms:activity_log'))
        self.assertEqual(resp.status_code, 302)
        self.assertIn('/accounts/login/', resp['Location'])

    def test_activity_log_loads_empty(self):
        resp = self.client.get(reverse('platforms:activity_log'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Activity Log')

    def test_activity_log_shows_entries(self):
        p = make_platform()
        make_activity(p, title='Deployed the thing')
        resp = self.client.get(reverse('platforms:activity_log'))
        self.assertContains(resp, 'Deployed the thing')

    def test_activity_log_filter_by_platform(self):
        p1 = make_platform(name='Alpha', slug='alpha')
        p2 = make_platform(name='Beta', slug='beta')
        make_activity(p1, title='Alpha work')
        make_activity(p2, title='Beta work')
        resp = self.client.get(reverse('platforms:activity_log') + '?platform=alpha')
        self.assertContains(resp, 'Alpha work')
        self.assertNotContains(resp, 'Beta work')

    def test_activity_log_filter_by_type(self):
        p = make_platform()
        make_activity(p, title='Dev work', activity_type=ActivityType.DEVELOPMENT)
        make_activity(p, title='Infra work', activity_type=ActivityType.INFRASTRUCTURE)
        resp = self.client.get(reverse('platforms:activity_log') + '?type=development')
        self.assertContains(resp, 'Dev work')
        self.assertNotContains(resp, 'Infra work')

    def test_activity_log_milestones_filter(self):
        p = make_platform()
        make_activity(p, title='Regular entry', is_milestone=False)
        make_activity(p, title='Big milestone', is_milestone=True)
        resp = self.client.get(reverse('platforms:activity_log') + '?milestones=1')
        self.assertContains(resp, 'Big milestone')
        self.assertNotContains(resp, 'Regular entry')

    def test_activity_log_newest_first(self):
        from datetime import timedelta
        p = make_platform()
        now = timezone.now()
        make_activity(p, title='Old', occurred_at=now - timedelta(days=5))
        make_activity(p, title='New', occurred_at=now)
        resp = self.client.get(reverse('platforms:activity_log'))
        content = resp.content.decode()
        self.assertLess(content.index('New'), content.index('Old'))

    def test_add_activity_get(self):
        resp = self.client.get(reverse('platforms:activity_add'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Log Activity')

    def test_add_activity_post(self):
        p = make_platform()
        resp = self.client.post(reverse('platforms:activity_add'), {
            'title': 'Something happened',
            'activity_type': 'development',
            'occurred_at': timezone.now().strftime('%Y-%m-%dT%H:%M'),
            'description': '',
            'ref_url': '',
            'is_milestone': False,
        })
        self.assertRedirects(resp, reverse('platforms:activity_log'))
        self.assertEqual(ActivityEntry.objects.filter(title='Something happened').count(), 1)

    def test_edit_activity(self):
        p = make_platform()
        e = make_activity(p, title='Original title')
        resp = self.client.post(
            reverse('platforms:activity_edit', kwargs={'pk': e.pk}),
            {
                'title': 'Updated title',
                'activity_type': 'deployment',
                'occurred_at': timezone.now().strftime('%Y-%m-%dT%H:%M'),
                'description': '',
                'ref_url': '',
            }
        )
        e.refresh_from_db()
        self.assertEqual(e.title, 'Updated title')

    def test_delete_activity(self):
        p = make_platform()
        e = make_activity(p)
        resp = self.client.post(reverse('platforms:activity_delete', kwargs={'pk': e.pk}))
        self.assertEqual(ActivityEntry.objects.filter(pk=e.pk).count(), 0)


class PlatformActivityIntegrationTests(AuthenticatedTestCase):

    def test_platform_detail_shows_activity_section(self):
        p = make_platform()
        make_activity(p, title='Recent dev work')
        resp = self.client.get(reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertContains(resp, 'Activity')
        self.assertContains(resp, 'Recent dev work')

    def test_platform_activity_add(self):
        p = make_platform()
        resp = self.client.post(
            reverse('platforms:platform_activity_add', kwargs={'slug': p.slug}),
            {
                'title': 'Platform-specific activity',
                'activity_type': 'maintenance',
                'occurred_at': timezone.now().strftime('%Y-%m-%dT%H:%M'),
                'description': '',
                'ref_url': '',
            }
        )
        self.assertRedirects(resp, reverse('platforms:platform_detail', kwargs={'slug': p.slug}))
        self.assertEqual(p.activity_entries.filter(title='Platform-specific activity').count(), 1)

    def test_dashboard_shows_recent_activity(self):
        p = make_platform()
        make_activity(p, title='Dashboard activity entry')
        resp = self.client.get(reverse('platforms:dashboard'))
        self.assertContains(resp, 'Dashboard activity entry')
