# Generated by Django 6.1.1 on 2026-09-20 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('digitalocean', 'DigitalOcean'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure'), ('linode', 'Linode / Akamai'), ('hetzner', 'Hetzner'), ('custom', 'Custom / Self-hosted'), ('other', 'Other')], default='other', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=253)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('host_type', models.CharField(choices=[('vps', 'VPS'), ('dedicated', 'Dedicated Server'), ('container', 'Container / PaaS'), ('shared', 'Shared Hosting'), ('other', 'Other')], default='vps', max_length=20)),
                ('os_info', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('platform_type', models.CharField(choices=[('website', 'Website'), ('web_application', 'Web Application'), ('ecommerce', 'E-Commerce'), ('api', 'API'), ('internal_application', 'Internal Application'), ('other', 'Other')], default='website', max_length=30)),
                ('framework', models.CharField(choices=[('django', 'Django'), ('wagtail', 'Wagtail'), ('wordpress', 'WordPress'), ('laravel', 'Laravel'), ('custom', 'Custom'), ('other', 'Other')], default='other', max_length=30)),
                ('lifecycle_status', models.CharField(choices=[('idea', 'Idea'), ('development', 'Development'), ('staging', 'Staging'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('paused', 'Paused'), ('archived', 'Archived')], default='development', max_length=20)),
                ('default_environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='platforms.platform')),
            ],
            options={
                'ordering': ['-is_primary', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('other', 'Other')], default='github', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='platforms.platform')),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('web', 'Web Application'), ('api', 'API'), ('worker', 'Background Worker'), ('database', 'Database'), ('cache', 'Cache'), ('queue', 'Queue'), ('other', 'Other')], default='web', max_length=20)),
                ('runtime_identifier', models.CharField(blank=True, max_length=200)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='platforms.host')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='platforms.platform')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('error_info', models.TextField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='platforms.platform')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='platforms.service')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='success', max_length=20)),
                ('deployed_at', models.DateTimeField()),
                ('deployed_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='platforms.platform')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='platforms.service')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
    ]
