# Generated by Django 6.1.1 on 2026-09-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='framework_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='framework',
            field=models.CharField(choices=[('django', 'Django'), ('wagtail', 'Wagtail'), ('wordpress', 'WordPress'), ('laravel', 'Laravel'), ('oscar', 'Oscar'), ('custom', 'Custom'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
